"""Export service: generate a per-book Markdown summary."""
from __future__ import annotations

from datetime import datetime

from models.book import Book


def export_book_markdown(book: Book) -> str:
    """Render a :class:`Book` and its annotations as a Markdown string."""
    lines: list[str] = []

    lines.append(f"# {book.title}")
    if book.author:
        lines.append(f"**Author:** {book.author}")
    lines.append(f"**Source:** {book.source}")
    lines.append(f"**Exported by KoNotes:** {datetime.now().strftime('%Y-%m-%d')}")
    lines.append("")
    lines.append("---")
    lines.append("")

    highlights = [a for a in book.annotations if a.kind == "highlight"]
    notes = [a for a in book.annotations if a.kind == "note"]
    other = [a for a in book.annotations if a.kind == "unknown"]

    if highlights:
        lines.append(f"## Highlights ({len(highlights)})")
        lines.append("")
        for ann in highlights:
            if ann.chapter:
                lines.append(f"### {ann.chapter}")
            lines.append(f"> {ann.text}")
            meta_parts: list[str] = []
            if ann.location:
                meta_parts.append(f"Location: {ann.location}")
            if ann.created_at:
                meta_parts.append(ann.created_at.strftime("%Y-%m-%d"))
            if meta_parts:
                lines.append(f"*{' · '.join(meta_parts)}*")
            lines.append("")

    if notes:
        lines.append(f"## Notes ({len(notes)})")
        lines.append("")
        for ann in notes:
            if ann.chapter:
                lines.append(f"### {ann.chapter}")
            lines.append(f"**Note:** {ann.text}")
            if ann.location:
                lines.append(f"*Location: {ann.location}*")
            lines.append("")

    if other:
        lines.append(f"## Other Annotations ({len(other)})")
        lines.append("")
        for ann in other:
            lines.append(f"- {ann.text}")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by [KoNotes](https://github.com/texasbe2trill/KoNotes)*")

    return "\n".join(lines)
